spring:
  data:
    elasticsearch:
      uris: http://${ELASTICSEARCH_HOST:localhost}:${ELASTICSEARCH_PORT:9200}
      username: 
      password: 
      
elasticsearch:
  host: ${ELASTICSEARCH_HOST:localhost}
  port: ${ELASTICSEARCH_PORT:9200}
  scheme: http

logging:
  level:
    org.elasticsearch: INFO
    me.yunhui: DEBUG