spring:
  data:
    elasticsearch:
      uris: http://localhost:9200
      username: 
      password: 

elasticsearch:
  host: localhost
  port: 9200
  scheme: http

logging:
  level:
    org.elasticsearch: INFO
    org:
      elasticsearch:
        client: DEBUG
      apache:
        http: DEBUG
    me.yunhui: DEBUG

