name: PR Agent

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
  push:
    branches: [ main, master ]

jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    name: Run pr agent on every pull request, respond to user comments
    steps:
      - name: PR Agent action step
        id: pragent
        uses: qodo-ai/pr-agent@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOOGLE_AI_STUDIO__GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          CONFIG__MODEL: "gemini/gemini-1.5-flash"
          CONFIG__RESPONSE_LANGUAGE: "ko-KR"
